name: Node.js Package

on:
  push:
    branches:
      - develop

jobs:
  verify-and-publish-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - name: Install, test, and build
        working-directory: ./RTC-Made-Simple-Server
        run: |
          npm install
          npm run typecheck
          npm test
          npm run build
      - name: Publish to npm
        working-directory: ./RTC-Made-Simple-Server
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  verify-and-publish-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - name: Install, test, and build
        working-directory: ./RTC-Made-Simple-UI
        run: |
          npm install
          npm run typecheck
          npm test
          npm run build
      - name: Publish to npm
        working-directory: ./RTC-Made-Simple-UI
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
